Go back to having non-global file1 and file2
This doesn't work, but I'm recording it for posterity

e.g., when using --np 4:

cprnc --np 4 ~/cime/tools/cprnc/test_inputs/control.nc
~/cime/tools/cprnc/test_inputs/diffs_in_vals.nc

gives errors like:

TypeError: Required argument 'fileno' (pos 1) not found
Exception AttributeError: "'NetcdfFileScipy' object has no attribute '_copy'" in <bound method NetcdfFileScipy.__del__ of <cprnc_py.netcdf.netcdf_file_scipy.NetcdfFileScipy object at 0x10e877fd0>> ignored
Exception AttributeError: "'netcdf_file' object has no attribute 'fp'" in <bound method netcdf_file.close of <cprnc_py.netcdf.scipy.netcdf.netcdf_file object at 0x10e877710>> ignored
Process PoolWorker-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
Exception AttributeError: "'NetcdfFileScipy' object has no attribute '_copy'" in <bound method NetcdfFileScipy.__del__ of <cprnc_py.netcdf.netcdf_file_scipy.NetcdfFileScipy object at 0x10e88e050>> ignored
Exception AttributeError: "'netcdf_file' object has no attribute 'fp'" in     task = get()